name: api_studio
description: "A powerful in-app API debugging and inspection tool for Flutter. Supports Dio interception, persistent logs, edit-and-run, CURL export, and a beautiful inspector dashboard."
version: 1.0.4
homepage: https://github.com/princesaini-dev/api_studio
repository: https://github.com/princesaini-dev/api_studio
issue_tracker: https://github.com/princesaini-dev/api_studio/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.1.0
  path_provider: ^2.1.5
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter:
